version: '3.1'

services:
  db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/volumes/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: developer
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge